//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by win32.rc
//
#define IDI_VIBE                        5
#define IDD_SERVER                      101
#define IDD_TAB_STATUS                  101
#define IDD_INIT                        103
#define IDD_STARTUP                     103
#define IDD_CLEANUP                     104
#define IDR_MAINMENU                    105
#define IDD_USERSGROUPS                 107
#define IDD_USERS                       107
#define IDD_TAB_USERS                   107
#define IDD_SETTINGS                    108
#define IDD_TAB_SETTINGS                108
#define IDB_TOP                         109
#define IDD_SKINS                       109
#define IDD_SHARING                     110
#define IDD_TAB_SHARING                 110
#define IDD_SERVERSETTINGS              111
#define IDD_PAGE_SERVER                 111
#define IDB_ABOUT                       113
#define IDD_GENERAL                     116
#define IDD_PAGE_GENERAL                116
#define IDD_USER                        117
#define IDD_PAGE_USERSETUP              118
#define IDD_PAGE_USERGENERAL            119
#define IDD_INDEXING                    120
#define IDD_PERMISSION                  121
#define IDI_ICON1                       125
#define IDB_BITMAP1                     126
#define IDB_USERGROUP                   126
#define IDB_BITMAP2                     127
#define IDB_TOGGLE                      127
#define IDS_ALLOWED                     130
#define IDS_INVALIDIPADDRESS            131
#define IDS_VALUE                       132
#define IDS_ADDUSER                     133
#define IDS_EDITUSER                    134
#define IDS_CLOSING                     135
#define IDS_ADDGROUP                    136
#define IDS_EDITGROUP                   137
#define IDS_INVALIDGROUPNAME            138
#define IDS_GROUPEXISTS                 139
#define IDS_SETTINGS_AUTOSTART          140
#define IDS_SETTINGS_CONFIRMEXIT        141
#define IDS_KICKSESSION                 142
#define IDS_REALLYEXIT                  143
#define IDS_IDLE                        144
#define IDS_ANALYZING                   145
#define IDS_INDEXING                    146
#define IDS_VALIDATING                  147
#define IDS_EVERYONE                    148
#define IDS_SETTINGS_MINIMIZETOTRAY     149
#define IDS_ANY                         150
#define IDS_YES                         151
#define IDS_NO                          152
#define IDS_SERVERRUNNING               153
#define IDS_STATUS                      154
#define IDS_USERSGROUPS                 155
#define IDS_SHARING                     156
#define IDS_SETTINGS                    157
#define IDS_SECURITY                    158
#define IDS_ADD                         159
#define IDS_EDIT                        160
#define IDS_REMOVE                      161
#define IDS_SHAREEXISTS                 163
#define IDS_ADDSHARE                    164
#define IDS_EDITSHARE                   165
#define IDS_INDEXALL                    166
#define IDS_VIRTUALNAME                 167
#define IDS_PATH                        168
#define IDS_SIZE                        169
#define IDS_LASTINDEXED                 170
#define IDS_INITIALIZING                171
#define IDS_CLEAR                       172
#define IDS_TIME                        173
#define IDS_MESSAGE                     174
#define IDS_CONNECTEDSESSIONS           175
#define IDS_SERVERNOTRUNNING            176
#define IDS_NAME                        177
#define IDS_IPADDRESS                   178
#define IDS_CONNECTED                   179
#define IDS_START                       180
#define IDS_STOP                        181
#define IDS_INVALIDUSERNAME             182
#define IDS_INVALIDPASSWORD             183
#define IDS_USEREXISTS                  184
#define IDS_DELETE                      185
#define IDS_GROUPS                      186
#define IDS_USERS                       187
#define IDS_INVALIDVIRTUALNAME          188
#define IDS_INVALIDPATH                 189
#define IDS_SHOWWINDOW                  190
#define IDS_EXIT                        191
#define IDS_MINIMIZETOTRAY              192
#define IDS_FORMAT_CONNECTEDSESSIONS    193
#define IDS_RESTOREDEFAULTSETTINGS_CONFIRM 194
#define IDS_FORMAT_STREAMING            195
#define IDS_RESTOREDEFAULTSETTINGS      196
#define IDS_INDEXNEW                    197
#define IDS_SETTINGS_CHECKFORUPDATES    198
#define IDC_STATIC_MESSAGE              1002
#define IDC_STATIC_GROUP_STATUS         1005
#define IDC_STATIC_GROUP_SERVERSTATUS   1005
#define IDC_STATIC_GROUP_CONNECTEDSESSIONS 1006
#define IDC_STATIC_GROUP_SESSIONS       1006
#define IDC_STATIC_GROUP_SERVERLOG      1007
#define IDC_BUTTON_STOP                 1010
#define IDC_BUTTON_START                1011
#define IDC_LIST_CONNECTEDSESSIONS      1016
#define IDC_STATIC_GROUP_USERS          1017
#define IDC_STATIC_GROUP_GROUPS         1018
#define IDC_STATIC_GROUP_SHAREDDIRECTORIES 1020
#define IDC_STATIC_GROUP_INSTALLEDSKINS 1021
#define IDC_STATIC_GROUP_SETTINGS       1024
#define IDC_TREE_SETTINGS               1027
#define IDC_LIST_GROUPS                 1038
#define IDC_LIST_USERS                  1039
#define IDC_LIST_SERVERLOG              1039
#define IDC_LIST_SHAREPERMISSIONS       1039
#define IDC_LIST_SITEPERMISSIONS        1040
#define IDC_LIST_SESSIONS               1041
#define IDC_COMBO_IPADDRESS             1043
#define IDC_EDIT_PORT                   1044
#define IDC_LIST_OPTIONS                1047
#define IDC_STATIC_GROUP_LANGUAGEFILE   1048
#define IDC_EDIT_LANGUAGEFILE           1049
#define IDC_BUTTON_BROWSE               1050
#define IDC_STATIC_GROUP_OPTIONS        1051
#define IDC_EDIT1                       1053
#define IDC_EDIT_USERNAME               1053
#define IDC_EDIT_MAXSESSIONS            1053
#define IDC_EDIT_AUTOINDEXINTERVAL      1053
#define IDC_EDIT_CERTIFICATEFILE        1053
#define IDC_EDIT_IPADDRESS1             1053
#define IDC_EDIT_SSLCERTIFICATEFILE     1053
#define IDC_EDIT_SERVERLOG              1053
#define IDC_EDIT_FILEPATTERN            1053
#define IDC_EDIT2                       1054
#define IDC_EDIT_PASSWORD               1054
#define IDC_EDIT_VIRTUALNAME            1054
#define IDC_EDIT_CERTIFICATEKEYFILE     1054
#define IDC_EDIT_IPADDRESS2             1054
#define IDC_EDIT_SSLCERTIFICATEKEYFILE  1054
#define IDC_EDIT_ADDRESS                1054
#define IDC_CHECK_DISABLED              1055
#define IDC_EDIT5                       1055
#define IDC_EDIT_SESSIONTIMEOUT         1055
#define IDC_EDIT_IPADDRESS3             1055
#define IDC_EDIT_SSLCERTIFICATEKEYPASSWORD 1055
#define IDC_EDIT_FILENAME               1055
#define IDC_LIST1                       1056
#define IDC_LIST_USERSGROUPS            1056
#define IDC_BUTTON_CLOSE                1057
#define IDC_EDIT_IPADDRESS4             1057
#define IDC_STATIC_APPLICATION          1058
#define IDC_LIST_SHARES                 1060
#define IDC_BUTTON_SAVECHANGES          1061
#define IDC_STATIC_USERNAME             1063
#define IDC_STATIC_PASSWORD             1064
#define IDC_STATIC_VIRTUALNAME          1064
#define IDC_STATIC_GROUP_MEMBEROFGROUPS 1065
#define IDC_STATIC_GROUP_SETUP          1066
#define IDC_BUTTON                      1071
#define IDC_BUTTON2                     1072
#define IDC_CHECK_BROADCASTING          1073
#define IDC_CHECK_LISTENING             1074
#define IDC_BUTTON_ADDSHAREPERMISSION   1074
#define IDC_CHECK_MAXSESSIONSPERIP      1075
#define IDC_BUTTON_REMOVESHAREPERMISSION 1075
#define IDC_CHECK_MAXLISTEN             1076
#define IDC_BUTTON_EDITSHAREPERMISSION  1076
#define IDC_CHECK_BYPASS                1077
#define IDC_BUTTON_ADDSITEPERMISSION    1077
#define IDC_EDIT_MAXLISTEN              1078
#define IDC_BUTTON_REMOVESITEPERMISSION 1078
#define IDC_COMBO_MAXLISTENPERIOD       1079
#define IDC_BUTTON_EDITSITEPERMISSION   1079
#define IDC_BUTTON1                     1080
#define IDC_CHECK_MAXDOWNLOADSPEED      1080
#define IDC_BUTTON_CLEAR                1080
#define IDC_BUTTON_RESET                1080
#define IDC_BUTTON_CHECKAGAIN           1080
#define IDC_EDIT_MAXDOWNLOADSPEEDKBPS   1081
#define IDC_CHECK_BROWSEONLY            1082
#define IDC_CHECK_MAXSESSIONS           1083
#define IDC_EDIT_MAXSESSIONSPERIP       1084
#define IDC_STATIC_GROUP_GENERAL        1085
#define IDC_STATIC_GROUP_SHARELIMITS    1086
#define IDC_CHECK_MAXDOWNLOAD           1087
#define IDC_EDIT_MAXDOWNLOAD            1088
#define IDC_COMBO_MAXDOWNLOADPERIOD     1089
#define IDC_STATIC_KBPERSECOND          1090
#define IDC_STATIC_GROUP_BROADCASTING   1091
#define IDC_STATIC_GROUP_BROADCASTLISTENING 1092
#define IDC_STATIC_MBPER                1093
#define IDC_STATIC_GROUP_SHAREPERMISSIONS 1094
#define IDC_STATIC_GROUP_SITEPERMISSIONS 1095
#define IDC_STATIC_PATH                 1098
#define IDC_EDIT_PATH                   1099
#define IDC_STATIC_GROUP_ACCESSRULES    1100
#define IDC_BUTTON_ADD                  1101
#define IDC_BUTTON_REMOVE               1102
#define IDC_BUTTON_EDIT                 1103
#define IDC_LIST_PERMISSIONS            1104
#define IDC_PROGRESS                    1105
#define IDC_STATIC_GROUP_INDEXING       1106
#define IDC_CHECK_AUTOINDEX             1107
#define IDC_STATIC_AUTOINDEXINTERVAL    1108
#define IDC_STATIC_GROUP_SSLSETTINGS    1109
#define IDC_CHECK_ENABLED               1110
#define IDC_STATIC_CERTIFICATEFILE      1111
#define IDC_BUTTON_BROWSECERTIFICATEFILE 1112
#define IDC_BUTTON_BROWSESSLCERTIFICATEFILE 1112
#define IDC_BUTTON_BROWSECERTIFICATEKEYFILE 1113
#define IDC_STATIC_GROUP_LOGINSTATISTICS 1113
#define IDC_BUTTON_BROWSESSLCERTIFICATEKEYFILE 1113
#define IDC_STATIC_CERTIFICATEKEYFILE   1114
#define IDC_STATIC_GROUP_TRANSFERSSTATISTICS 1114
#define IDC_STATIC_GROUP_LOGINSTATISTICS2 1114
#define IDC_STATIC_VALUE_NUMBEROFLOGINS 1115
#define IDC_STATIC_VALUE_LASTLOGIN      1116
#define IDC_STATIC_VALUE_LASTKNOWNIP    1117
#define IDC_BUTTON_STARTSTOP            1118
#define IDC_STATIC_VALUE_TOTALSHARESTREAMING 1118
#define IDC_STATIC_SERVERSTATUS         1119
#define IDC_STATIC_VALUE_TOTALBROADCASTLISTENING 1119
#define IDC_STATIC_VALUE_STREAMEDTOTAL  1119
#define IDC_STATIC_CONNECTEDSESSIONS    1120
#define IDC_STATIC_VALUE_LISTENEDTODAY  1120
#define IDC_STATIC_KBSENTPERSECOND      1121
#define IDC_STATIC_VALUE_LISTENEDTHISWEEK 1121
#define IDC_STATIC_VALUE_SERVERSTATUS   1122
#define IDC_STATIC_VALUE_LISTENEDTHISMONTH 1122
#define IDC_STATIC_VALUE_CONNECTEDSESSIONS 1123
#define IDC_STATIC_VALUE_LISTENEDTOTAL  1123
#define IDC_STATIC_VALUE_KBSENTPERSECOND 1124
#define IDC_RADIO_ALLOW                 1125
#define IDC_RADIO_DENY                  1126
#define IDC_STATIC_GROUP_PERMISSION     1127
#define IDC_STATIC_GROUP_USERORGROUP    1128
#define IDC_STATIC_GROUP_IPADDRESS      1129
#define IDC_STATIC_ACTION               1130
#define IDC_STATIC_TIMEELAPSED          1131
#define IDC_STATIC_GROUP_PROGRESS       1132
#define IDC_STATIC_VALUE_PATH           1133
#define IDC_BUTTON_ABORT                1134
#define IDC_STATIC_VALUE_ACTION         1135
#define IDC_STATIC_VALUE_TIMEELAPSED    1136
#define IDC_STATIC_VALUE_PROGRESS       1138
#define IDC_COMBO_USERSGROUPS           1138
#define IDC_STATIC_VALUE_MESSAGE        1138
#define IDC_CHECK_IPADDRESSRESTRICTION  1141
#define IDC_STATIC_VALUE_STREAMEDTODAY  1142
#define IDC_STATIC_DAYDOWNLOAD          1142
#define IDC_STATIC_VALUE_STREAMEDTHISWEEK 1143
#define IDC_STATIC_WEEKDOWNLOAD         1143
#define IDC_STATIC_VALUE_STREAMEDTHISMONTH 1144
#define IDC_STATIC_MONTHDOWNLOAD        1144
#define IDC_EDIT_NAME                   1146
#define IDC_STATIC_NAME                 1147
#define IDC_CHECK_AUTOCONFIGUREROUTER   1148
#define IDC_EDIT_MAXSTREAMINGSPEEDKBPS  1153
#define IDC_CHECK_MAXSTREAMING          1154
#define IDC_EDIT_MAXSTREAMING           1155
#define IDC_COMBO_MAXSTREAMINGPERIOD    1156
#define IDC_CHECK_MAXSTREAMINGSPEED     1157
#define IDC_CHECK_MAXLISTENING          1159
#define IDC_EDIT_MAXLISTENING           1160
#define IDC_COMBO_MAXLISTENINGPERIOD    1161
#define IDC_CHECK_SSLENABLED            1163
#define IDC_COMBO_FILEPATTERNS          1165
#define IDC_CHECK_INCLUDEHIDDENFILES    1167
#define IDC_CHECK_INCLUDEHIDDEN         1167
#define IDC_CHECK_BROADCASTER           1168
#define IDC_CHECK_LISTENER              1169
#define IDC_CHECK_BROWSER               1170
#define IDC_CHECK_BYPASSLIMITS          1171
#define IDC_CHECK_MAXBANDWIDTH          1172
#define IDC_EDIT_MAXBANDWIDTH           1173
#define IDC_STATIC_TOTALDOWNLOAD        1174
#define IDC_STATIC_DESCRIPTION          1187
#define IDC_STATIC_GROUP                1188
#define IDC_CHECK_TRANSCODER            1189
#define IDC_STATIC_WHATISTHIS           1191
#define IDC_STATIC_STATUS               1192
#define IDC_STATIC_DOWNLOADLINK         1193
#define IDC_CHECK_ADMIN                 1207
#define IDD_ABOUT                       9102
#define IDD_PAGE_USERSTATISTICS         9103
#define IDD_SHARE                       9106
#define IDD_PAGE_SHARESETUP             9107
#define IDD_PAGE_SHAREPERMISSIONS       9108
#define IDD_TAB_SECURITY                9110
#define IDD_PAGE_GROUPSETUP             9113
#define IDD_GROUP                       9114
#define IDD_PAGE_GROUPGENERAL           9115
#define IDD_SERVERMONITOR               9117
#define IDD_PAGE_SSL                    9118
#define IDD_PAGE_LOGGING                9120
#define IDD_PAGE_INDEXING               9121
#define IDD_PAGE_USERTRANSCODING        9124
#define IDD_PAGE_GROUPTRANSCODING       9125
#define IDD_PAGE_TRANSCODING            9126
#define IDD_UPDATE                      9127
#define IDC_ABOUT_LOGO                  25525
#define IDC_STATIC_WEB                  25527
#define IDC_STATIC_URL                  25527
#define IDC_STATIC_EMAIL                25528
#define IDC_STATIC_COPYRIGHT            25529
#define ID_FILE_EXIT                    40001
#define ID_FILE_RESTOREDEFAULTSETTINGS  40002
#define ID_VIEW_INDEXINGPROGRESS        40003
#define ID_WINDOW_MINIMIZETOTRAY        40004
#define ID_HELP_ABOUT                   40005
#define ID_HELP_DOCUMENTATION           40006
#define ID_HELP_CHECKFORUPDATES         40007
#define ID_VIEW_REFRESH                 40013
#define ID_VIEW_SERVERMONITOR           40015
#define ID_HELP_WEBSITE                 40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1209
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
